version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # This line tells to not make any changes to the node_modules folder
      # in the app folder
      - /app/node_modules
      # Copy everything in the server folder and add it to the main
      # app folder 
      - ./server:/app
    environment:
      # Inside a docker compose file we don't need to specify the host IP
      # for a service, since the service is created inside this file as well
      # and we can access it directly by that given name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=db
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    #
  # 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    #
  # 
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
